services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MAX_ALLOWED_PACKET: 56777216 # 56MB
      MYSQL_ROOT_PASSWORD: root
    networks:
      - database
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    networks:
      - database
    environment:
      - PMA_ARBITRARY=1

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - database

networks:
  database:
    driver: bridge
